The most exercises are taken from here: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb

# 1. Initialize numpy array and a python list with 1 million integers and multiply each element by a constant.

In [1]:
import numpy as np

numpy_array = np.arange(int(1e6))

a_list = list(range(int(1e6)))

%timeit -n 100 numpy_array2 = numpy_array*2

1.61 ms ± 129 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [2]:
%timeit -n 10 a_list2 = [x * 2 for x in a_list]

49.9 ms ± 2.24 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 2. Create a null vector of size 10

In [3]:
zero_array = np.zeros(10)
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 3. How to find the memory size of any array?

In [7]:
print(zero_array.size * zero_array.itemsize)

80


In [8]:
zero_array2 = np.zeros((10,10))
print(zero_array2)
print("Memory size: " + str(zero_array2.size * zero_array2.itemsize))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Memory size: 800


# 4. How to get the documentation of the numpy add function from the command line?

In [9]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

# 5. Create a null vector of size 10 but the fifth value which is 1.

In [11]:
zeros_array3 = np.zeros(10)
zeros_array3[4] = 1
print(zeros_array3)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 6. Create a vector with values ranging from 10 to 49

In [12]:
array_arange = np.arange(10,50,1)
print(array_arange)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 7. Reverse a vector (first element becomes last).

In [15]:
array_arange_reverse = array_arange[::-1]
print(array_arange_reverse)
print(array_arange)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 8. Create a 3x3 matrix with values ranging from 0 to 8.

In [17]:
squared_matrix1 = np.arange(0,9)
squared_matrix1 = squared_matrix1.reshape((3,3))
print(squared_matrix1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 9. Find indices of non-zero elements from [1,2,0,0,4,0].

In [19]:
array1 = np.array([1,2,0,0,4,0])
non_zero_indeces = np.where(array1 > 0)
print(non_zero_indeces)

(array([0, 1, 4]),)


# 10. Create a 3x3 identity matrix.

In [21]:
identity_matrix1 = np.identity(3)
print(identity_matrix1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 11. Create a 3x3x3 array with random values.

In [26]:
random_array_3d = np.random.rand(3,3,3)
print(random_array_3d)
print(random_array_3d.shape)

[[[0.24062592 0.17447437 0.66231033]
  [0.73131553 0.74241787 0.35979306]
  [0.54165466 0.87292732 0.15713185]]

 [[0.87178406 0.60741486 0.92445193]
  [0.06703905 0.10543253 0.43775684]
  [0.97002979 0.11550045 0.4344629 ]]

 [[0.74163781 0.25876774 0.65156346]
  [0.53834504 0.94541635 0.27214656]
  [0.51568595 0.03304403 0.33190792]]]
(3, 3, 3)


# 12. Create a 10x10 array with random values and find the minimum and maximum values.

In [29]:
random_array_2d = np.random.rand(10,10)
print("Min: " + str(np.min(random_array_2d)))
print("Max: " + str(np.max(random_array_2d)))

Min: 0.001573487153343267
Max: 0.9924178129972205


# 13. Create a random vector of size 30 and find the mean value. 

In [33]:
random_array_1d = np.random.rand(30)
print("Mean: " + str(random_array_1d.mean()))

Mean: 0.5423018398687203


# 14. Create a 2d array with 1 on the border and 0 inside.

In [34]:
array2 = np.zeros((10,10))
array2[:,0] = 1.0
array2[0,:] = 1.0
array2[:,-1] = 1.0
array2[-1,:] = 1.0
print(array2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 15. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [42]:
matrix3 = np.zeros((5,5))
np.fill_diagonal(matrix3[1:], np.arange(1, 5))
print(matrix3)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 16. Create a 5x5 matrix with values 1,2,3,4 just above the diagonal.

In [43]:
matrix4 = np.zeros((5,5))
np.fill_diagonal(matrix4[:,1:], np.arange(1, 5))
print(matrix4)

[[0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0.]]


# 17. Create a 8x8 matrix and fill it with a checkerboard pattern.

In [64]:
matrix5 = np.zeros((8,8))
array_checker_1d = np.ones(8)
array_checker_1d[::2] = 0
matrix5[:] = array_checker_1d
matrix5[::2] = array_checker_1d[::-1]
print(matrix5)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

NumPy arrays are stored in row-major order (C-order), meaning the last index changes fastest,so <br/>
* x dimension stride $= 7 \times 8 = 56$
* y dimension stride $= 8$
* z dimension stride $= 1$
So the answer is: <br/>
$(1,5,3)$

# 19. Create a checkerboard 8x8 matrix using the tile function.

In [70]:
pattern_array = np.array([[1,0],[0,1]])
matrix_checker = np.zeros((8,8))
matrix_checker = np.tile(pattern_array, (4,4))
print(matrix_checker)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 20. Normalize a 5x5 random matrix

In [74]:
random_matrix = np.random.rand(5,5)
print(random_matrix)
print()
print(random_matrix / np.linalg.norm(random_matrix))

[[0.44986919 0.68120753 0.93974457 0.51009784 0.82082764]
 [0.47409315 0.31078447 0.03592148 0.3205494  0.05786229]
 [0.89083909 0.64414911 0.9459071  0.73608498 0.89117206]
 [0.57079301 0.71532591 0.53358111 0.49215745 0.81191659]
 [0.75916952 0.71183099 0.7018749  0.42353023 0.4792349 ]]

[[0.13976848 0.21164228 0.29196636 0.15848074 0.25502043]
 [0.14729455 0.09655668 0.01116034 0.09959051 0.01797706]
 [0.27677207 0.20012871 0.29388098 0.22869199 0.27687552]
 [0.17733793 0.22224242 0.16577668 0.15290689 0.25225188]
 [0.23586406 0.22115659 0.21806336 0.13158531 0.14889203]]
